###############################################################################
# THE HOME ASSISTANT CONFIGURATION FILE - MOTHER OF ALL CONFIG FILES
# @Author   :   Mahasri Kalavala
###############################################################################
homeassistant:
  name: Home 
  temperature_unit: F
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  
  unit_system: imperial
  time_zone: !secret time_zone
  customize_glob: !include customize_glob.yaml
  customize_domain: !include customize_domain.yaml
  packages: !include_dir_named packages
  # whitelist_external_dirs:
  #   - '/home/homeassistant/.homeassistant/www'


sun:
alexa:
cloud:
config:
discovery:
homekit:
  autostart: true
python_script:

# updater:
# logbook:
# history:
# recorder:
#  db_url: !secret my_sql_url

# influxdb:
#  host: 192.168.1.125
#  include:
#    entities:
#      - sensor.dining_room_thermostat_temperature
#      - sensor.downstairs_multi_sensor_temperature
#      - sensor.front_room_multi_sensor_temperature
#      - sensor.guest_bedroom_multi_sensor_temperature
#      - sensor.tv_multi_sensor_temperature

mqtt:
  broker: !secret pi_hole_mqtt_server
  port: !secret pi_hole_mqtt_port
  username: !secret pi_hole_mqtt_username
  password: !secret pi_hole_mqtt_password
  keepalive: 60
  client_id: pi_ha

http:
  api_password: !secret api_password
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.1.0/24
    - 192.168.200.0/24
    - 10.10.1.0/24
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 3

binary_sensor:
  - platform: workday
    country: US

emulated_hue:
  expose_by_default: false
  host_ip: !secret ha_ip_address
  listen_port: 8300
  exposed_domains:
    - light
    - switch
    - input_boolean

logger: !include logging.yaml
group: !include_dir_merge_named groups

panel_iframe:
  front_room_ha:
    title: Front Room HA
    icon: mdi:home-assistant
    url: !secret front_room_ha_url
  tv_room_ha:
    title: TV Room HA
    icon: mdi:home-assistant
    url: !secret tv_room_ha_url
  snapcast_server:
    title: Snapcast Server
    icon: mdi:music
    url: !secret snapcast_server_url

ios:
  push:
    categories:
      - name: Single Car Garage Door
        identifier: '1CAR_GARAGE'
        actions:
          - identifier: '1CAR_GARAGE_CLOSE'
            title: 'Close Garage Door'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
      - name: Two Car Garage Door
        identifier: '2CAR_GARAGE'
        actions:
          - identifier: '2CAR_GARAGE_CLOSE'
            title: 'Close Garage Door'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
      - name: Trash Recycle
        identifier: 'trash_recycle'
        actions:
          - identifier: 'TRASH_LEFT'
            title: 'Done'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
          - identifier: 'TRASH_REMIND_LATER'
            title: 'Remind Later'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
      - name: Welcome Home
        identifier: 'welcome_home'
        actions:
          - identifier: 'DISABLE_SECURITY'
            title: 'Yes'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
