default: warning
logs:
  gsp: warning
  root: warning
  openzwave: warning
  libopenzwave: warning
  py.warnings: critical
  aiohttp.server: warning
  homeassistant.setup: warning
  homeassistant.core: warning
  homeassistant.exceptions: warning
  homeassistant.helpers.script: warning  
  homeassistant.helpers.entity: warning
  homeassistant.components.http: warning
  homeassistant.components.zwave: warning
  homeassistant.components.sensor: warning
  homeassistant.components.recorder: warning
  homeassistant.components.discovery: warning
  custom_components.sensor.command_line: warning
  custom_components.sensor.paloalto: warning
  custom_components.sensor.life360: warning
  homeassistant.components.automation: warning
  homeassistant.components.climate.nest: warning
  homeassistant.components.media_player: warning
  homeassistant.components.device_tracker: warning
  custom_components.media_player.sharptv: warning
  homeassistant.components.emulated_hue: warning
  homeassistant.components.camera.generic: warning
