default: critical
logs:
  gsp: critical
  root: critical
  openzwave: critical
  libopenzwave: critical
  py.warnings: critical
  aiohttp.server: critical
  homeassistant.setup: critical
  homeassistant.core: critical
  homeassistant.exceptions: critical
  homeassistant.helpers.script: critical  
  homeassistant.helpers.entity: critical
  homeassistant.components.http: critical
  homeassistant.components.zwave: critical
  homeassistant.components.sensor: critical
  homeassistant.components.recorder: critical
  homeassistant.components.discovery: critical
  custom_components.sensor.command_line: critical
  custom_components.sensor.paloalto: critical
  custom_components.sensor.life360: critical
  homeassistant.components.automation: critical
  homeassistant.components.climate.nest: critical
  homeassistant.components.media_player: critical
  homeassistant.components.device_tracker: critical
  custom_components.media_player.sharptv: critical
  homeassistant.components.emulated_hue: critical
  homeassistant.components.camera.generic: critical
