homeassistant:
  customize:

    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'xiaomi'

      exposed: &exposed
        <<: *customize
        emulated_hue_hidden: true
        homebridge_hidden: false
        critical: true

      not_exposed: &not_exposed
        <<: *customize
        emulated_hue_hidden: false
        homebridge_hidden: true
        critical: false

      hidden: &hidden
        <<: *customize
        hidden: true
        critical: false

    binary_sensor.motion_sensor_158d0001a662fe:
      friendly_name: Kitchen Motion Sensor (Xiaomi)
    sensor.Illumination_158d0001a662fe:
      friendly_name: Kitchen Luminance (Xiaomi)
     
    binary_sensor.motion_sensor_158d0001a25041:
      friendly_name: Family Room Motion Sensor (xiaomi)
    sensor.Illumination_158d0001a25041:
      friendly_name: Family Room Luminance (xiaomi)
 
    binary_sensor.motion_sensor_158d00016db6d2:
      friendly_name: Front Room Motion Sensor (Xiaomi)
    sensor.Illumination_158d00016db6d2:
      friendly_name: Front Room Luminance (Xiaomi)
    
    binary_sensor.motion_sensor_158d00016c2d0e:
      friendly_name: Dining Room Motion Sensor (Xiaomi)
    sensor.Illumination_158d00016c2d0e:
      friendly_name: Dining Room Luminance (Xiaomi)

    binary_sensor.motion_sensor_158d00024e57d3:
      friendly_name: Master Bedroom Motion Sensor (Xiaomi)
    sensor.illumination_158d00024e57d3:
      friendly_name: Master Bedroom Luminance (Xiaomi)

    binary_sensor.motion_sensor_158d00024ee084:
      friendly_name: Front Door Motion Sensor (Xiaomi)
    sensor.illumination_158d00024ee084:
      friendly_name: Front Door Luminance (Xiaomi)

    binary_sensor.motion_sensor_158d00024e842c:
      friendly_name: Srinikas Bedroom Motion Sensor (Xiaomi)
    sensor.illumination_158d00024e842c:
      friendly_name: Srinika's Bedroom Luminance (Xiaomi)

    binary_sensor.motion_sensor_158d00024e57fb:
      friendly_name: Hasikas Bedroom Motion Sensor (Xiaomi)
    sensor.illumination_158d00024e57fb:
      friendly_name: Hasika's Bedroom Luminance (Xiaomi)

    sensor.Illumination_34ce008ad65d:
      friendly_name: Hallway Luminance (Xiaomi Aqara)

    light.gateway_light_34ce008ad65d:
      friendly_name: Hallway Light (Xiaomi Aqara Gateway)

    binary_sensor.cube_158d0002794cd6:
      friendly_name: Living Room Cube (Xiaomi)
    
    binary_sensor.cube_158d000278eb6a:
      friendly_name: Master Bedroom Cube (Xiaomi)

    binary_sensor.cube_158d000276e3e8:
      friendly_name: Basement Cube (Xiaomi)

group:
  Xiaomi Aqara:
    entities:
      - binary_sensor.motion_sensor_158d0001a662fe
      - binary_sensor.motion_sensor_158d0001a25041
      - binary_sensor.motion_sensor_158d00016db6d2
      - binary_sensor.motion_sensor_158d00016c2d0e
      - binary_sensor.motion_sensor_158d00024e57d3
      - binary_sensor.motion_sensor_158d00024ee084
      - binary_sensor.motion_sensor_158d00024e842c
      - binary_sensor.motion_sensor_158d00024e57fb

      - sensor.illumination_158d00024e57d3
      - sensor.illumination_158d00024ee084
      - sensor.illumination_158d0001a662fe
      - sensor.illumination_158d0001a25041
      - sensor.illumination_158d00016db6d2
      - sensor.illumination_158d00016c2d0e
      - sensor.illumination_158d00024e842c
      - sensor.illumination_158d00024e57fb
      - sensor.illumination_34ce008ad65d
      
      - binary_sensor.cube_158d0002794cd6
      - binary_sensor.cube_158d000276e3e8
      - binary_sensor.cube_158d000278eb6a

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_key

automation:

# Living Room Magic Cube
#   - Flip 90     : Toggle Family Room Lights
#   - Flip 180    : Lights ON Family Room Lights FULL brightness
#   - Move        : Toggle Kitchen Light
#   - Double Tap  : Turn OFF Downstairs Lights
#   - Shake       : Toggle Do Not Disturb Mode
  - alias: Cube event flip90
    initial_state: true
    hide_entity: true
    trigger:
      platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_158d0002794cd6
        action_type: flip90
    action:
      - service: light.toggle
        entity_id: light.family_room
  - alias: Cube event flip180
    initial_state: true
    hide_entity: true
    trigger:
      platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_158d0002794cd6
        action_type: flip180
    action:
      - service: light.turn_on
        entity_id: light.family_room
        data:
          brightness: 254
  - alias: Cube event move
    initial_state: true
    hide_entity: true
    trigger:
      platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_158d0002794cd6
        action_type: move
    action:
      - service: switch.toggle
        entity_id: switch.kitchen_light
  - alias: Cube event tap_twice
    initial_state: true
    hide_entity: true
    trigger:
      platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_158d0002794cd6
        action_type: tap_twice
    action:
      - service: homeassistant.turn_off
        entity_id: group.downstairs_lights
  - alias: Cube event shake_air
    initial_state: true
    hide_entity: true
    trigger:
      platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_158d0002794cd6
        action_type: shake_air
    action:
      - service: input_boolean.toggle
        entity_id: input_boolean.do_not_disturb

# Front Room Magic Cube
#   - Flip 90     : Toggle Front Room Lights
#   - Flip 180    : Turn ON Downstairs Lights
#   - Move        : Toggle Office Room Lights
#   - Double Tap  : Turn OFF Downstairs Lights
#   - Shake       : Toggle Do Not Disturb Mode
  - alias: Cube event flip90
    initial_state: true
    hide_entity: true
    trigger:
      platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_158d000276e3e8
        action_type: flip90
    action:
      - service: switch.toggle
        entity_id: switch.rf_switch_four
  - alias: Cube event move
    initial_state: true
    hide_entity: true
    trigger:
      platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_158d000276e3e8
        action_type: move
    action:
      - service: switch.toggle
        entity_id: switch.office_room_lights
  - alias: Cube event tap_twice
    initial_state: true
    hide_entity: true
    trigger:
      platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_158d000276e3e8
        action_type: tap_twice
    action:
      - service: homeassistant.turn_off
        entity_id: group.downstairs_lights
  - alias: Cube event flip180
    initial_state: true
    hide_entity: true
    trigger:
      platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_158d000276e3e8
        action_type: flip180
    action:
      - service: homeassistant.turn_on
        entity_id: group.downstairs_lights  
  - alias: Cube event shake_air
    initial_state: true
    hide_entity: true
    trigger:
      platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_158d000276e3e8
        action_type: shake_air
    action:
      - service: input_boolean.toggle
        entity_id: input_boolean.do_not_disturb

# Master Bedroom Magic Cube Actions
  #   - Flip 90     : All Lights OFF (upstairs and downstairs)
  #   - Flip 180    : Toggle Lights
  #   - Move        : Turn ON Master Bedroom Lights
  #   - Double Tap  : Toggle On ALL upstairs Lights
  #   - Shake       : Toggle Do Not Disturb Mode
  - alias: Master Bedroom Cube event flip90
    initial_state: true
    hide_entity: true
    trigger:
      platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_158d000278eb6a
        action_type: flip90
    action:
      - service: homeassistant.turn_off
        entity_id: group.downstairs_lights
      - service: homeassistant.turn_off
        entity_id: group.upstairs_lights

  - alias: Master Bedroom Cube event flip180
    initial_state: true
    hide_entity: true
    trigger:
      platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_158d000278eb6a
        action_type: flip180
    action:
      - service: light.toggle
        entity_id: light.master_bedroom

  - alias: Master Bedroom Cube event move
    initial_state: true
    hide_entity: true
    trigger:
      platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_158d000278eb6a
        action_type: move
    action:
      - service: light.turn_on
        entity_id: light.master_bedroom

  - alias: Master Bedroom Cube event tap_twice
    initial_state: true
    hide_entity: true
    trigger:
      platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_158d000278eb6a
        action_type: tap_twice
    action:
      - service: homeassistant.toggle
        entity_id: group.upstairs_lights

  - alias: Master Bedroom Cube event shake_air
    initial_state: true
    hide_entity: true
    trigger:
      platform: event
      event_type: cube_action
      event_data:
        entity_id: binary_sensor.cube_158d000278eb6a
        action_type: shake_air
    action:
      - service: input_boolean.toggle
        entity_id: input_boolean.do_not_disturb


# Before you think this code is crazy, here is an explanation.
#
# I have a xiaomi aqara PIR motion sensor near the front door, and when it triggers, I capture photo
# from the camera, save it locally using last_triggered date and time... and then send that image 
# to my email as an attacment.
#
# In the action, I have multiple services I am calling, and one service creates file, and I needed
# that file name in the second service. Since I can't pass info between the services within an action,
# I generate the file name based on the automation's last_triggered date, and that info is same across
# all the services, and I can access the file name ;)
#
# I only send iOS notifications when I am home, as my HA is not exposed to Internet, and I can't see my camera 
# unless I login to my vpn on my device. That's why you see the condition right above iOS notification service.
#
# Make sure you add the path to the white_list in the configuration.yaml file.
#

  - alias: Motion Detected at Front Door
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d00024ee084
      to: 'on'
    action:
      - service: script.voice_notify
        data:
          message: 'Someone is at the front door'
          greeting: 'no'
      - service: camera.snapshot
        data_template:
          entity_id: "camera.frontdoor_camera"
          filename: "{{ '/home/homeassistant/.homeassistant/www/downloads/camera/frontdoor/frontdoor_' ~  (states.automation.motion_detected_at_front_door.attributes.last_triggered ~ '').replace('-','_').replace(' ', '_').replace(':','_').replace('.','_').replace('+','_') ~ '.jpg' }}"
      - service: notify.notify_smtp
        data_template:
          title: 'Front door motion {{ now().strftime("%d %h %Y, %H %M:%S %p") }}'
          message: 'Motion detected at the front door!'
          data:
            images:
              - "{{ '/home/homeassistant/.homeassistant/www/downloads/camera/frontdoor/frontdoor_' ~  (states.automation.motion_detected_at_front_door.attributes.last_triggered ~ '').replace('-','_').replace(' ', '_').replace(':','_').replace('.','_').replace('+','_') ~ '.jpg' }}"
      - condition: template
        value_template: "{{ states.device_tracker.suresh_suresh.state == 'home' }}"
      - service: notify.ios_devices
        data_template:
          message: "Check Front Door camera!"
          data:
            push:
              category: camera
            entity_id: "camera.frontdoor_camera"
            attachment:
              url: "{{ states.camera.frontdoor_camera.attributes.entity_picture }}"
              content-type: jpg
